package com.zopnote.android.merchant.data.model;

import android.support.annotation.NonNull;

import java.io.Serializable;

public class DraftInvoiceItem implements Serializable, Comparable<DraftInvoiceItem>{
    private String item;
    private double amount;
    private boolean autoGenerated;

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    @Override
    public int compareTo(@NonNull DraftInvoiceItem o) {
        return this.item.compareTo(o.item);
    }
}
